### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Soundscape/iOS app](https://hosted.weblate.org/projects/soundscape/ios-app/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by JJGatchalian** [comment]
Before commiting this pull request, I suggest we change the name of the "Enter Vicinity Distance" button because that phrase is hard to translate to Spanish. The word "enter" is tricky. I tried translating using the term more commonly used for going inside physical places, but another translator suggested using the term more commonly used for data entry. I think it's ok to just drop the word "enter," and the function still makes sense.

**Comment by steinbro** [comment]
I agree that the "enter" is unnecessary. The reason it's there is because there's actually a second parameter in the code, Leave Vicinity Distance, but it's not configurable (it's calculated relative to the Enter Vicinity Distance).  I think "Audio Mute Distance" is a good replacement.

**Comment by JJGatchalian** [comment]
Thanks. I'll change it to "Audio Mute Distance." In the future, if we ever
add the "Auto Unmute" feature I proposed in another issue, it might be a
better idea to call it "Delayed Start" to avoid too much repetition. Also
that phrase is a bit of an Easter egg because it's a nod to Soundscape's
Microsoft roots because of Windows services that have a "Delayed Start"
even though the phrase is pretty generic at the same time.

**Comment by JJGatchalian** [comment]
I've just changed the translation to "Audio Mute Distance." We shouldn't close this pull request until the changes show up in the Weblate fork. I'll let you know when that happens.

**Comment by JJGatchalian** [comment]
It looks like Weblate has just merged my changes into the Weblate fork. After merging this pull request, "Enter Vicinity Distance" will be officially changed to "Audio Mute Distance."

**Pull request merged**
